// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcbeypxmyzlnejxsmfif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjYmV5cHhteXpsbmVqeHNtZmlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwNzIxMjEsImV4cCI6MjA1ODY0ODEyMX0.rd-GTN9_W7ADiMKpCxrJFGbovNTu8QiJXR5UCX_r8Eg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);